server:
  port: 8080

spring:
  application:
    name: eduvault-backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  storage:
    local-dir: ${user.home}/eduvault-data/files
  firebase:
    service-account-path: ${FIREBASE_CREDENTIALS_PATH:} # Optional if using mock or default credentials
    project-id: ${FIREBASE_PROJECT_ID:eduvault-mvp}
  gemini:
    api-key: AIzaSyA9Fvf6Ezazy3tAW8wx25kXvjZSWzx8QXM
